### ISSUE TITLE
missing a param in the tutorial

### ISSUE THREAD

**Issue by KevinColemanInc** [fullstackio/yelp-clone#3]
I think instead of

```
ReactDOM.render(
  <App history={browserHistory} />, mountNode);
```

it needs to be

```
ReactDOM.render(
  <App history={browserHistory} routes={routes} />, mountNode);
```

![image](https://cloud.githubusercontent.com/assets/2381771/15994533/2b5f1d2e-30bc-11e6-92aa-cf712a894ceb.png)

**Comment by auser** [comment]
Ah thanks for the bug report @KevinColemanInc. We don't have routes yet there in the post. Think we should create a dummy route at that point or do you think it's resolved later in the post?

**Comment by KevinColemanInc** [comment]
@auser if you scroll up a bit:

![image](https://cloud.githubusercontent.com/assets/2381771/16058549/e178ff76-3233-11e6-99bc-70008d169c4d.png)

I think your requiring the router to be passed in, but then in your example code when you scroll down (my initial post), you aren't passing it in, so it wasn't working for me.
